goes:
  bands: [8, 9, 10, 11, 13, 14, 15, 16]
  patch_x_length_pixels: 28
  patch_y_length_pixels: 28
  time_range_minutes: 10
  bt: False
  path: /mnt/mlnas01/mlsoundings/goes16
raob:
  profile_dims: 2048
  alt_el: 18000
  path: /mnt/mlnas01/mlsoundings/raobs
  valid_files_path: /mnt/data1/stock/mlsoundings/raobs/profiles-alt-files-processed.txt
rtma:
  rtma_type: [LPI, LRI, LTI]
  patch_x_length_pixels: 28
  patch_y_length_pixels: 28
  time_range_minutes: 40
  path: /mnt/mlnas01/mlsoundings/rtma
nwp:
  nwp_dims: 50
  time_range_minutes: 60
  path: /mnt/data1/stock/mlsoundings/rap
  wgrib2: /home/stock/bin/grib2/wgrib2/wgrib2
output_path: /mnt/data1/stock/mlsoundings/processed
