goes:
  bands: [8, 9, 10, 11, 13, 14, 15, 16]
  patch_x_length_pixels: 3
  patch_y_length_pixels: 3
  time_range_minutes: 10
  bt: False
  path: /mnt/mlnas01/mlsoundings/goes16
raob:
  profile_dims: 256
  path: /mnt/mlnas01/mlsoundings/raobs
  valid_sgp_files_path: # /mnt/data1/stock/mlsoundings/raobs/profiles-alt-files-processed.txt
  noaa_mutli_path: /mnt/mlnas01/mlsoundings/raobs/noaa-esrl
rtma:
  rtma_type: [LPI, LRI, LTI]
  patch_x_length_pixels: 3
  patch_y_length_pixels: 3
  time_range_minutes: 60
  path: /mnt/mlnas01/mlsoundings/rtma
nwp:
  nwp_dims: 256
  time_range_minutes: 60
  path: /mnt/mlnas01/grasso/cira
  wgrib2: /home/stock/bin/grib2/wgrib2/wgrib2
output_path: /mnt/data1/stock/mlsoundings/processed
date_regex: 202006
top_window_boundary: 17000
